### ISSUE TITLE
Forcing ppsspp_cheats to always being enabled makes it so you can't get hardcore retroachievements

### ISSUE THREAD

**Issue by Rolen47** [fabricecaruso/batocera-ports#31]
In LibRetro.CoreOptions.cs the setting ppsspp_cheats is always set to be enabled. This disables hardcore retroachievements every time I load a game with Retrobat. Is it necessary to lock it to being enabled?

**Comment by fabricecaruso** [comment]
ok i commited a fix for that. Cheats will be disabled when retroachievements are set to hardcore mode
